site_name: baixue11
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    scheme: default
    primary: deep purple
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

